@host=https://localhost:7224
POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Kirill",
    "lastName": "Pavlov",
    "email": "smr@gmail.com",
    "password": "123pwd"
} 